name: image-publisher

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        required: true
        default: latest

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push docker images
      env:
        IMAGE_REGISTRY: ghcr.io/teamziax/ocs-operator
        REGISTRY_NAMESPACE: ocs-operator
        IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG }}
      run: |
        make bundle
